name: scfet
services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    networks:
      - scfet_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./WebApi/uploads:/app/uploads
      - ./WebApi/Backups:/app/Backups
    user: root
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${DB_NAME};Username=postgres;Password=${DB_PASSWORD}
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionStrings=redis-cache:6379,password=${Redis_PASSWORD},abortConnect=false,connectTimeout=5000,syncTimeout=5000
      - JwtSettings__Secret=${JWT_Secret}
      - CloudPud__Ip=${Host_Base_Url}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - DOCKER_NETWORK=scfet_network
      - DOTNET_GCHeapHardLimit=0x20000000 # 512 MB
    deploy:
      resources:
        limits:
          memory: 384M
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    ports:
      - "5050:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 1 bash -c 'echo > /dev/tcp/localhost/8080' || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    restart: on-failure

  telegramBot:
    image: telegrambot
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile
    networks:
      - scfet_network
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionStrings=redis-cache:6379,password=${Redis_PASSWORD},abortConnect=false,connectTimeout=5000,syncTimeout=5000
      - TelegramBot__UseProxy=${Use_Proxy}
      - TelegramBot__Proxy__Host=${Proxy_Host}
      - TelegramBot__Proxy__Port=${Proxy_Port}
      - TelegramBot__Proxy__Type=${Proxy_Type}
      - TelegramBot__Token=${TG_Students_TOKEN}
      - Api__BaseUrl=${Api_Base_Url}
      - App_Url=${App_Url}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_GCHeapHardLimit=0x8000000 # 128 MB
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      webapi:
        condition: service_healthy
    restart: on-failure

  telegrambotadministrators:
    image: telegrambotadministrators
    build:
      context: .
      dockerfile: TelegramBotAdministrators/Dockerfile
    networks:
      - scfet_network
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionStrings=redis-cache:6379,password=${Redis_PASSWORD},abortConnect=false,connectTimeout=5000,syncTimeout=5000
      - TelegramBot__Token=${TG_Administartors_TOKEN}
      - TelegramBot__UseProxy=${Use_Proxy}
      - TelegramBot__Proxy__Host=${Proxy_Host}
      - TelegramBot__Proxy__Port=${Proxy_Port}
      - TelegramBot__Proxy__Type=${Proxy_Type}
      - Api__BaseUrl=${Api_Base_Url}
      - App_Url=${App_Url}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_GCHeapHardLimit=0x8000000 # 128 MB
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      webapi:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    restart: on-failure

  telegrambotemployee:
    image: telegrambotemployee
    build:
      context: .
      dockerfile: TelegramBotEmployee/Dockerfile
    networks:
      - scfet_network
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionStrings=redis-cache:6379,password=${Redis_PASSWORD},abortConnect=false,connectTimeout=5000,syncTimeout=5000
      - TelegramBot__Token=${TG_Employee_TOKEN}
      - TelegramBot__UseProxy=${Use_Proxy}
      - TelegramBot__Proxy__Host=${Proxy_Host}
      - TelegramBot__Proxy__Port=${Proxy_Port}
      - TelegramBot__Proxy__Type=${Proxy_Type}
      - App_Url=${App_Url}
      - Api__BaseUrl=${Api_Base_Url}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_GCHeapHardLimit=0x8000000 # 128 MB
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      webapi:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    restart: on-failure

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - scfet_network
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - scfet_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx384m -Xms192m"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  #redis
  redis-cache:
    image: redis:7-alpine
    command: redis-server --requirepass ${Redis_PASSWORD}
    networks:
      - scfet_network
    volumes:
      - redis_cache_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-session:
    image: redis:7-alpine
    networks:
      - scfet_network
    command: redis-server --requirepass sessionpassword
    volumes:
      - redis_session_data:/data

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=ru_RU.UTF-8'
    networks:
      - scfet_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5433:5432"
    restart: unless-stopped

networks:
  scfet_network:
    name: scfet_network
    driver: bridge

volumes:
  redis_cache_data:
  redis_session_data:
  postgres_data:
