// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321080544_PhoneNumberUniqueRollback")]
    partial class PhoneNumberUniqueRollback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a6b8c9d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "ИТ-21"
                        },
                        new
                        {
                            Id = new Guid("5d4c3b2a-1f0e-9d8c-7b6a-5f4e3d2c1b0a"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "БУ-21"
                        },
                        new
                        {
                            Id = new Guid("9e8f7a6b-5c4d-3e2f-1a0b-9c8d7e6f5a4b"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "ИТ-22"
                        },
                        new
                        {
                            Id = new Guid("b0a1c2d3-e4f5-6a7b-8c9d-e0f1a2b3c4d5"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Исип22/1"
                        });
                });

            modelBuilder.Entity("Core.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Core.Models.NotificationReceiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("NotificationId", "UserId")
                        .IsUnique();

                    b.ToTable("NotificationReceivers");
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8d7e6f5-a4b3-c2d1-e0f9-8a7b6c5d4e3f"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Email = "admin@scfet.ru",
                            FirstName = "Администратор",
                            IsActive = true,
                            LastName = "Системы",
                            PasswordHash = "10000.KtO5UPCwLgoZiPkTPcBFdg==.GnqlYRsAlmYbaoEHbrgC7ISjPuArcsKmYHgmJ0fPTy8=",
                            PhoneNumber = "",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("f4e5d6c7-b8a9-0f1e-2d3c-4b5a6f7e8d9c"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@scfet.ru",
                            FirstName = "Администратор2",
                            IsActive = true,
                            LastName = "Системы",
                            PasswordHash = "10000.KtO5UPCwLgoZiPkTPcBFdg==.GnqlYRsAlmYbaoEHbrgC7ISjPuArcsKmYHgmJ0fPTy8=",
                            PhoneNumber = "",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("2a3b4c5d-6e7f-89a0-b1c2-d3e4f5a6b7c8"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Email = "teacher@scfet.ru",
                            FirstName = "Иван",
                            IsActive = true,
                            LastName = "Преподаватель",
                            PasswordHash = "10000.SR7TWPsSkx86MW5kqhsk9g==.fmFOgSZurlhe/T6sBgfgE7V9liHsKaCdybPEyXCXREA=",
                            PhoneNumber = "",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("9b8c7d6e-5f4a-3b2c-1d0e-f9a8b7c6d5e4"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Email = "teacher2@scfet.ru",
                            FirstName = "Алексей",
                            IsActive = true,
                            LastName = "Преподаватель",
                            PasswordHash = "10000.SR7TWPsSkx86MW5kqhsk9g==.fmFOgSZurlhe/T6sBgfgE7V9liHsKaCdybPEyXCXREA=",
                            PhoneNumber = "",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("7e6d5c4b-3a29-1f0e-dcba-9876f5e4d3c2"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Email = "student@scfet.ru",
                            FirstName = "Михаил",
                            IsActive = true,
                            LastName = "Студент",
                            PasswordHash = "10000.ubXk5yxtgQgWcc3/M+w4eQ==.U2b8/891ganlfSu1GvNNjx8OvTjPz9DBwRl6jT/SPwM=",
                            PhoneNumber = "",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("d3c2b1a0-9f8e-7d6c-5b4a-392817f6e5d4"),
                            CreatedAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Email = "student2@scfet.ru",
                            FirstName = "Вася",
                            IsActive = true,
                            LastName = "Студент",
                            PasswordHash = "10000.ubXk5yxtgQgWcc3/M+w4eQ==.U2b8/891ganlfSu1GvNNjx8OvTjPz9DBwRl6jT/SPwM=",
                            PhoneNumber = "",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("Core.Models.Notification", b =>
                {
                    b.HasOne("Core.Models.User", "Sender")
                        .WithMany("SentNotifications")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Core.Models.NotificationReceiver", b =>
                {
                    b.HasOne("Core.Models.Notification", "Notification")
                        .WithMany("Receivers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.User", "User")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.HasOne("Core.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Core.Models.Notification", b =>
                {
                    b.Navigation("Receivers");
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.Navigation("ReceivedNotifications");

                    b.Navigation("SentNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
